#include<stdio.h>
#include<conio.h>
main()
{
int a=1,b=2,c=3,d=4;
clrscr();
if(a>b)
{
  if(a>c)
  {
  printf("a is big");
  }
  else
  {
  printf("c is big");
  }


}
 if(a>d)
 {
   if(c>d)
   {
   printf("c1 is big");
   }
   else
   {
   printf("d is big");
   }
 }
 if(b>d)
 {
   if(b>d)
   {
   printf("b is big");
   }
   else
   {
   printf("d1 is big");
   }
 }
 if(c>d)
 {
 printf("c2 is big");
 }
 else
 {
 printf("d2 is big");
 }
getch();
}














